"""Query alias expansion rules for code search."""

from __future__ import annotations

_QUERY_ALIASES: dict[str, tuple[str, ...]] = {
    "api": ("endpoint", "route"),
    "arg": ("argument",),
    "args": ("argument", "arguments"),
    "argument": ("arg", "args"),
    "arguments": ("arg", "args", "argument"),
    "auth": ("authentication", "authorization"),
    "authentication": ("auth",),
    "authorization": ("auth",),
    "body": ("payload",),
    "cfg": ("config", "configuration"),
    "config": ("cfg", "configuration"),
    "configuration": ("cfg", "config"),
    "class": ("cls",),
    "cls": ("class",),
    "cmd": ("command",),
    "command": ("cmd",),
    "conn": ("connection",),
    "connection": ("conn",),
    "context": ("ctx",),
    "ctx": ("context",),
    "ctor": ("constructor",),
    "constructor": ("ctor",),
    "database": ("db",),
    "dao": ("repository",),
    "db": ("database",),
    "deserialize": ("serde",),
    "dir": ("directory",),
    "directory": ("dir",),
    "endpoint": ("api", "route"),
    "env": ("environment",),
    "environment": ("env",),
    "err": ("error",),
    "error": ("err",),
    "errors": ("err", "error"),
    "exc": ("exception",),
    "exception": ("exc",),
    "fake": ("mock", "stub"),
    "fixture": ("fixtures",),
    "fixtures": ("fixture",),
    "flag": ("option",),
    "flags": ("option", "options"),
    "filesystem": ("fs",),
    "fn": ("function",),
    "fs": ("filesystem",),
    "func": ("function",),
    "function": ("fn", "func"),
    "handle": ("handler",),
    "handler": ("handle",),
    "hdr": ("header", "headers"),
    "header": ("hdr",),
    "headers": ("hdr", "header"),
    "iface": ("interface",),
    "impl": ("implementation",),
    "implementation": ("impl",),
    "init": ("initialize", "initialization"),
    "initialization": ("init",),
    "initialize": ("init",),
    "interface": ("iface",),
    "log": ("logger", "logging"),
    "logger": ("log", "logging"),
    "logging": ("log", "logger"),
    "marshal": ("serialize",),
    "message": ("msg",),
    "messages": ("msg", "message"),
    "mock": ("stub", "fake"),
    "msg": ("message",),
    "opt": ("option",),
    "opts": ("option", "options"),
    "option": ("opt", "opts", "flag"),
    "options": ("opt", "opts", "option", "flags"),
    "param": ("parameter",),
    "params": ("parameter", "parameters"),
    "parameter": ("param", "params"),
    "parameters": ("param", "params", "parameter"),
    "parse": ("parser",),
    "parser": ("parse",),
    "payload": ("body",),
    "pkg": ("package",),
    "package": ("pkg",),
    "req": ("request",),
    "repo": ("repository",),
    "repository": ("repo",),
    "request": ("req",),
    "requests": ("req", "request"),
    "res": ("response",),
    "resp": ("response",),
    "response": ("resp", "res"),
    "responses": ("resp", "res", "response"),
    "route": ("endpoint",),
    "routes": ("route", "endpoint"),
    "serde": ("serialize", "deserialize"),
    "serialize": ("serde",),
    "spec": ("test", "tests"),
    "stack": ("trace", "stacktrace"),
    "stacktrace": ("stack", "trace"),
    "stderr": ("error",),
    "stdin": ("input",),
    "stdout": ("output",),
    "stub": ("mock", "fake"),
    "temp": ("tmp", "temporary"),
    "temporary": ("tmp", "temp"),
    "test": ("spec",),
    "tests": ("test", "spec"),
    "tmp": ("temp", "temporary"),
    "trace": ("stacktrace",),
    "transaction": ("tx", "txn"),
    "tx": ("transaction",),
    "txn": ("transaction",),
    "unmarshal": ("deserialize",),
    "validate": ("validation", "validator"),
    "validation": ("validate", "validator"),
    "validator": ("validate", "validation"),
}


def query_aliases(term: str) -> tuple[str, ...]:
    """Return code-search aliases for one normalized query term."""
    return _QUERY_ALIASES.get(term.lower(), ())
